# Generated by Django 2.2 on 2019-04-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution', models.CharField(default='Will Rogers', max_length=127)),
                ('text', models.TextField()),
            ],
        ),
    ]
